spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/teumteum
    username: root
    password: root

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%X{traceId}] [%-5level] %logger{36} - %msg%n"
  level:
    root: INFO
    com.likelion.teumteum: DEBUG